import Head from 'next/head'
import Home from './Home/index.page'

export default function App() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      <main>
        <Home />
      </main>
    </>
  )
}
